# Generated by Django 4.1.7 on 2023-02-25 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
