# Generated by Django 4.1.7 on 2023-03-05 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0009_pokemon_title_eg_pokemon_title_jp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='title_eg',
            new_name='title_en',
        ),
    ]
