# Generated by Django 4.1.7 on 2023-03-08 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0017_alter_pokemon_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='next_evolution',
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='photo',
            field=models.ImageField(default='ghost.png', upload_to='', verbose_name='изображение'),
        ),
    ]
