# Generated by Django 4.1.7 on 2023-03-08 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0018_remove_pokemon_next_evolution_alter_pokemon_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='previous_evolution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_pokemon', to='pokemon_entities.pokemon', verbose_name='из кого эволюционировал'),
        ),
    ]
