# Generated by Django 4.1.7 on 2023-03-10 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0025_alter_pokemon_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='photo',
            field=models.ImageField(default='default_image.png', upload_to='', verbose_name='изображение'),
        ),
    ]
